### ISSUE TITLE
New python import structure does not work if SIO backend is not built

### ISSUE THREAD

**Issue by kjvbrt** [AIDASoft/podio#489]
when using `podio-dump` compiled in nightlies stack `__version__.py` is not installed to install directory, when installed the circular dependency emerges:
```
Traceback (most recent call last):
  File "/home/jsmiesko/Work/FCC/podio/install/bin/podio-dump", line 10, in <module>
    from podio import __version__
  File "/home/jsmiesko/Work/FCC/podio/install/python/podio/__init__.py", line 25, in <module>
    from . import root_io, sio_io, reading
ImportError: cannot import name 'sio_io' from partially initialized module 'podio' (most likely due to a circular import) (/home/jsmiesko/Work/FCC/podio/install/python/podio/__init__.py)
```

 - OS version: AlmaLinux9
 - Compiler version: GCC 11.3.1
 - PODIO version: d402f747877239aaedefe993856e26749c91bea3=develop-z47c5e
 - Reproduced by: compile latest version of podio in nightlies stack
 - Input: any root file
 - Output: see above
 - Goal: dump a file

**Comment by tmadlener** [comment]
After some debugging, we found that:

- `__version__.py` is not installed when installing the `python/podio` directory via cmake, because of 
https://github.com/AIDASoft/podio/blob/0cf68a89328441a1e7afb88b13bd7af93a302a95/python/CMakeLists.txt#L22

- The uncoditional import of `sio_io` fails and raises a confusing error which hides the fact that ROOT wasn't able to load the dictionary in this case

**Comment by tmadlener** [comment]
Just for completeness, this was introduced with #459
