### ISSUE TITLE
Undeclared identifiers when including data model headers in cling

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#892]
We are encountering errors when loading analysis macros when upgrading from podio 1.3 to 1.6 (and keeping root 6.38.00 and EDM4hep 0.99.1 constant). See e.g. https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/6875585

We have minimized the issue to the test.C below. This compiles when explicit (`root -l -q -b test.C+`) but not when letting ROOT handle it (no plus sign). Unlikely related to Python.h, I think. Maybe header ordering, but also looks fine to me...

test.C
```cpp
#include "edm4hep/MCParticle.h"

int test(){
  return 0;
}
```

```console
$ root -l -b -q test.C+

Processing test.C+...
Info in <TUnixSystem::ACLiC>: creating shared library /home/wdconinc/./test_C.so
(int) 0
```

```console
$ root -l -b -q test.C 2>&1 | head

Processing test.C...
libedm4hepDict dictionary payload:741:7: error: field has incomplete type '::edm4hep::Vector3f'
      referencePoint{}; ///< Reference point of the track parameters, e.g. the origin at the IP, or the position  of the
      ^
libedm4hepDict dictionary forward declarations' payload:8:26: note: forward declaration of 'edm4hep::Vector3f'
namespace edm4hep{class  Vector3f;}
                         ^
libedm4hepDict dictionary payload:2177:59: error: use of undeclared identifier 'MCParticleObj'
  explicit MutableMCParticle(podio::utils::MaybeSharedPtr<MCParticleObj> obj);
```

The error related to `referencePoint` only shows up in some systems (my local test system) but not in our CI systems linked above. The error for `MCParticleObj` is consistent though.

**Comment by wdconinc** [comment]
```diff
diff --git a/python/templates/selection.xml.jinja2 b/python/templates/selection.xml.jinja2                                                                      index b9d37245..b1248209 100644
--- a/python/templates/selection.xml.jinja2                                     +++ b/python/templates/selection.xml.jinja2                                     @@ -39,6 +39,9 @@
 {# Otherwise the python interface does not work in gcc builds #}                {# Additionally, in order to allow "direct" access to the user facing classes #}                                                                                {# we have to declare them here, otherwise they cannot be easily imported #}
+{# Obj classes must be included for ROOT dictionary forward declarations #}
+{# to work correctly with inline functions that reference them #}
+{{ class_selection(class, postfix='Obj') }}
 {{ class_selection(class, prefix='Mutable') }}
 {{ class_selection(class) }}
 {{ class_selection(class, postfix='Collection') }}
```

This ensures that the Obj files are included (and forward declared) in the dictionary source code.
